<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>craft</string>
		<string>sfs</string>
	</array>
	<key>name</key>
	<string>KSP configuration</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Anything after 2 slashes is a comment.</string>
			<key>match</key>
			<string>\s*((//).*$\n?)</string>
			<key>name</key>
			<string>comment.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Alphanumeric characters inside square brackets is a parameter.</string>
			<key>match</key>
			<string>(?&lt;=[\|\[])([A-Za-z0-9\*_]*)(?=[\]\|])</string>
			<key>name</key>
			<string>variable.parameter.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Alphanumeric characters after a colon is a ModuleManager function.</string>
			<key>match</key>
			<string>(?&lt;=:)([A-Za-z0-9]*)</string>
			<key>name</key>
			<string>support.function.modulemanager.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Anything before an equal sign is a key in the key-value pairs.</string>
			<key>match</key>
			<string>([A-Za-z0-9_,]*\s*)(?=([\*\+])?=)</string>
			<key>name</key>
			<string>keyword.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>32 hexadecimal characters after an equal sign is a pid.</string>
			<key>match</key>
			<string>(?&lt;==)(\s*[0-9a-f]{32})</string>
			<key>name</key>
			<string>constant.numeric.pid.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Alphanumeric characters split by 4 hyphens after an equal sign is a guid.</string>
			<key>match</key>
			<string>(?&lt;==)(\s*([a-z0-9]+\-){4}[a-z0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.guid.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>'True' or 'False' after an equal sign is a boolean.</string>
			<key>match</key>
			<string>(?&lt;==)(\s*([Tt]rue|[Ff]alse))</string>
			<key>name</key>
			<string>constant.numeric.boolean.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>'NaN', 'Infinity', or 'None' after an equal sign is a non-numeric constant.</string>
			<key>match</key>
			<string>(?&lt;==)(\s*(NaN|Infinity|None))</string>
			<key>name</key>
			<string>constant.numeric.nan.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Anything else after an equal sign containing alphabetical characters is a string.</string>
			<key>match</key>
			<string>(?&lt;==)(\s?.*[A-Za-z].*)</string>
			<key>name</key>
			<string>string.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric characters, including scientific notation, is a number.</string>
			<key>match</key>
			<string>(?&lt;=[=,\s\(])(\s*-?[0-9\.]+E?-?[0-9\.]*)</string>
			<key>name</key>
			<string>constant.numeric.ksp.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Anything else matching these symbols is a class name.</string>
			<key>match</key>
			<string>[A-Za-z0-9\*_\./]*</string>
			<key>name</key>
			<string>entity.name.class.ksp.cfg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.ksp.cfg</string>
	<key>uuid</key>
	<string>2e22ffdc-c42e-4308-819d-c125852f1fb7</string>
</dict>
</plist>
